repos:
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      language_version: python3.8
      args: [--line-length=120]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.0a2
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    - id: mixed-line-ending
      args: [--fix=lf]
    - id: pretty-format-json
      args: [--autofix, --no-sort-keys]